apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260627-200218-lbtca72w38h0-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260627-200218-lbtca72w38h0.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260627-200218-lbtca72w38h0-service
            port:
              number: 80
