apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260627-200218-lbtca72w38h0-service
spec:
  selector:
    app: enterprise-system-20260627-200218-lbtca72w38h0
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
